blank_issues_enabled: false
contact_links:
  - name: Report an issue about the 3R4 Documentation
    url: https://github.com/Atlas-OS/docs/issues/
    about: Report all documentation issues in our 'docs' repository issue tracker.
  - name: Report a non-3R4 related issue
    url: https://github.com/Atlas-OS/Atlas/discussions
    about: Please report any non-3R4 Playbook related issue in the 'Bug Report' section on GitHub Discussions (website, Discord bot, etc.).
