---
title: Add Theme
description: Adds and sets the 3R4 themes by default
actions:
    # Apply theme file and set recent themes
  - !powerShell:
    command: |
      .\3R4Modules\initPowerShell.ps1
      Set-Theme -Path """$([Environment]::GetFolderPath('Windows'))\Resources\Themes\3R4-v1.0.x-dark.theme"""
      Set-ThemeMRU
    wait: true
    exeDir: true
    runas: currentUserElevated

    # Applies 3R4 lockscreen background
    # Also disables fun facts, tips, tricks, and more on lockscreen - only on Enterprise/Education
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization'
    value: 'LockScreenOverlaysDisabled'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'RotatingLockScreenEnabled'
    data: '0'
    type: REG_DWORD
  - !powerShell:
    command: |
      foreach ($userKey in (Get-ChildItem "HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI\Creative").PsPath) {
          Set-ItemProperty -Path $userKey -Name 'RotatingLockScreenEnabled' -Type DWORD -Value 0 -Force
      }
    exeDir: true
    wait: true
  - !powerShell:
    command: |
      .\3R4Modules\initPowerShell.ps1
      Set-LockscreenImage
    exeDir: true
    wait: true
    runas: currentUserElevated

    # Set 3R4 theme as default for new users
  - !registryValue:
    path: 'HKCU\Software\Policies\Microsoft\Windows\Personalization'
    value: 'ThemeFile'
    data: '%windir%\Resources\Themes\3R4-v1.0.x-dark.theme'
    type: REG_SZ
